# Generated by Django 2.1.2 on 2019-04-24 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id_issue', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=200)),
                ('issue_desc', models.TextField()),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='id_status',
            field=models.ForeignKey(db_column='id_stage', null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Status'),
        ),
    ]
