# Generated by Django 2.1.2 on 2019-04-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Status'),
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
