# Generated by Django 2.1.2 on 2019-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_urgent',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
