# Generated by Django 2.1.2 on 2019-04-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20190424_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_desc',
            new_name='description',
        ),
    ]
