# Generated by Django 2.1.2 on 2019-04-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20190424_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'RequestType',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='id_type',
            field=models.ForeignKey(db_column='id_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.RequestType'),
        ),
    ]
