# Generated by Django 2.1.2 on 2019-05-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_auto_20190531_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'managed': True, 'ordering': ['-time']},
        ),
        migrations.AlterModelTable(
            name='issuecomment',
            table='IssueComment',
        ),
    ]
