# Generated by Django 2.1.2 on 2019-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_issue_collaborators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='iss_type',
        ),
        migrations.RenameField(
            model_name='requesttype',
            old_name='type',
            new_name='iss_type',
        ),
    ]
